name: Is PR title mergeable

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check_if_pr_title_is_mergeable:
    name: Check if PR title is mergeable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: smikheiev/action-is-pr-title-mergeable@choose_keywords_to_support
        with: 
          # config for WIP keyword
          wip: >
            {
              "shouldCheck": false
            }
          # config for PENDING keyword
          pending: >
            {
              "shouldCheck": false
            }
          # config for RFC keyword
          rfc: >
            {
              "shouldCheck": true
            }
