name: Is PR title mergeable

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check_if_pr_title_is_mergeable:
    name: Check if PR title is mergeable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: smikheiev/action-is-pr-title-mergeable@add_labels
        with:
          wip: > # config for WIP keyword
            {
              "shouldCheck": true,
              "shouldAddLabel": true 
            }
          pending: > # config for PENDING keyword
            {
              "shouldCheck": true,
              "shouldAddLabel": true 
            }
          rfc: > # config for RFC keyword
            {
              "shouldCheck": false,
              "shouldAddLabel": true 
            }
          token: ${{ secrets.GITHUB_TOKEN }}
